### ISSUE TITLE
License under MIT

### ISSUE THREAD

**Issue by XtremeDevX** [sreechar/twttr#1]
Due to most of the source code being based off https://github.com/thomaswang/minimal-twitter, according to the MIT license:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

You must include the MIT License if using code from the minimal twitter repository as part of the twtter codebase.

**Comment by roblox34** [comment]
@sreechar

**Comment by sreechar** [comment]
> Due to most of the source code being based off https://github.com/thomaswang/minimal-twitter, according to the MIT license:
> 
> > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> 
> You must include the MIT License if using code from the minimal twitter repository as part of the twtter codebase.

https://github.com/sreechar/twttr/blob/main/credits/License.md :)
Consulted with Thomas Wang and made the necessary update.
Commit got delayed as i was out of station and the delay is regretted 👍 

Goodwill
// @sreechar
