### ISSUE TITLE
Will there be a Firefox extension please?

### ISSUE THREAD

**Issue by janemanthorpe** [sreechar/twttr#3]
Hi Sreecharan,
(I  hope  I spelled your name right, got it from Twitter :))
I love your  Twttr tool for blocking  adds on Chrome, and  wondered if you  are working  on an Firefox extension ?
From your Github page its says its coming :) and wondered a date planned?
Kind Regards
Jane

**Comment by akshithio** [comment]
There's one right here: https://addons.mozilla.org/en-US/firefox/addon/twttr/

Edit: It's been there since 2 months, the README.md just needs to be updated
